name = "glesha"
version = "0.1.3"
description = "SHA-2 for Gleam"
gleam = ">= 0.32.0"

licences = ["MIT"]
repository = { type = "github", user = "bunopnu", repo = "glesha" }

[dependencies]
gleam_stdlib = "~> 0.32"

[dev-dependencies]
gleeunit = "~> 0.11"

[javascript.deno]
allow_read = ["./"]
