name = "glesha2"
version = "0.1.0"
description = "SHA-2 for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "bunopnu", repo = "glesha2" }

[dependencies]
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.10"

[javascript.deno]
allow_read = ["./"]
