name = "glesha"
version = "0.1.4"
description = "SHA-2 for Gleam"
gleam = ">= 1.0.0"

licences = ["MIT"]
repository = { type = "github", user = "bunopnu", repo = "glesha" }

[dependencies]
gleam_stdlib = "~> 0.36"

[dev-dependencies]
gleeunit = "~> 1.1"

[javascript.deno]
allow_read = ["./"]
